package com.acme;

import com.acme.statusmgr.beans.RealSystemInfo;
import com.acme.statusmgr.beans.ServerStatusDecorator;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        ServerStatusDecorator.setSystemInfo(new RealSystemInfo());
        SpringApplication.run(Application.class, args);
    }
}
